from enum import IntEnum
from typing import Optional

from sqlalchemy.orm import declared_attr
from sqlmodel import Field, SQLModel

from .utils import table_name


class SQLModel_(SQLModel):
    @declared_attr
    def __tablename__(cls) -> str:
        return table_name(cls.__name__)


class PropertyInformation(SQLModel, table=True):
    __tablename__ = "properties"
    id: Optional[int] = Field(default=None, primary_key=True)
    gis_pin: str = Field(unique=True)
    absentee: Optional[int] = None
    account: Optional[str] = None
    acreage: Optional[float] = None
    additional_lots: Optional[str] = None
    additional_lots_parsed: Optional[str] = None
    assessed_1: Optional[float] = None
    assessed_2: Optional[float] = None
    assessed_3: Optional[float] = None
    assessed_4: Optional[float] = None
    bank_code: Optional[str] = None
    block: Optional[str] = None
    building_assmnt_1: Optional[float] = None
    building_assmnt_2: Optional[float] = None
    building_assmnt_3: Optional[float] = None
    building_assmnt_4: Optional[float] = None
    building_class: Optional[str] = None
    building_desc: Optional[str] = None
    calculated_taxes: Optional[float] = None
    calculated_taxes_year: Optional[int] = None
    census_block: Optional[str] = None
    census_code: Optional[str] = None
    census_county: Optional[str] = None
    census_state: Optional[str] = None
    census_tract: Optional[str] = None
    city_state_zip: Optional[str] = None
    city_state_zip_1: Optional[str] = None
    city_state_zip_2: Optional[str] = None
    city_state_zip_3: Optional[str] = None
    city_state_zip_4: Optional[str] = None
    class_4_code: Optional[str] = None
    corporate_owned: Optional[bool] = None
    county_name: Optional[str] = None
    deduction_amount: Optional[str] = None
    deed_book: Optional[str] = None
    deed_page: Optional[str] = None
    direct_parties: Optional[str] = None
    disabled_cnt: Optional[str] = None
    district_name: Optional[str] = None
    epl_desc: Optional[str] = None
    epl_facility_name: Optional[str] = None
    epl_further: Optional[str] = None
    epl_init: Optional[str] = None
    epl_own: Optional[str] = None
    epl_statute: Optional[str] = None
    epl_use: Optional[str] = None
    exempt_1: Optional[str] = None
    exempt_2: Optional[str] = None
    exempt_3: Optional[str] = None
    exempt_4: Optional[str] = None
    is_redacted: Optional[str] = None
    land_assmnt_1: Optional[float] = None
    land_assmnt_2: Optional[float] = None
    land_assmnt_3: Optional[float] = None
    land_assmnt_4: Optional[float] = None
    land_desc: Optional[str] = None
    last_year_tax: Optional[str] = None
    lot: Optional[str] = None
    map_page: Optional[str] = None
    mortgage_account: Optional[str] = None
    mun_updated: Optional[str] = None
    municipality: Optional[str] = None
    nu_code: Optional[str] = None
    o_city: Optional[str] = None
    o_state: Optional[str] = None
    o_zip: Optional[str] = None
    owner_1: Optional[str] = None
    owner_2: Optional[str] = None
    owner_3: Optional[str] = None
    owner_4: Optional[str] = None
    owner_mail_city: Optional[str] = None
    owner_mail_cmra: Optional[str] = None
    owner_mail_company: Optional[str] = None
    owner_mail_corrections: Optional[str] = None
    owner_mail_crrt: Optional[str] = None
    owner_mail_deliverable: Optional[str] = None
    owner_mail_dpv: Optional[str] = None
    owner_mail_dpv_notes: Optional[str] = None
    owner_mail_error_code: Optional[str] = None
    owner_mail_false_positive: Optional[str] = None
    owner_mail_house_num: Optional[str] = None
    owner_mail_left_overs: Optional[str] = None
    owner_mail_line_of_travel: Optional[str] = None
    owner_mail_no_stats: Optional[str] = None
    owner_mail_pbsa: Optional[str] = None
    owner_mail_post_dir: Optional[str] = None
    owner_mail_pre_dir: Optional[str] = None
    owner_mail_rdi: Optional[str] = None
    owner_mail_result_code: Optional[str] = None
    owner_mail_state: Optional[str] = None
    owner_mail_street: Optional[str] = None
    owner_mail_street2: Optional[str] = None
    owner_mail_street_name: Optional[str] = None
    owner_mail_sud: Optional[str] = None
    owner_mail_suffix: Optional[str] = None
    owner_mail_suite: Optional[str] = None
    owner_mail_unit_num: Optional[str] = None
    owner_mail_usps_bar_code: Optional[str] = None
    owner_mail_vacant_status: Optional[str] = None
    owner_mail_zip: Optional[str] = None
    owner_mail_zip4: Optional[str] = None
    owners_mailing_address: Optional[str] = None
    owners_name: Optional[str] = None
    p_city: Optional[str] = None
    p_state: Optional[str] = None
    p_zip: Optional[str] = None
    prior_block: Optional[str] = None
    prior_gis_pin: Optional[str] = None
    prior_lot: Optional[str] = None
    prior_qual: Optional[str] = None
    prop_mail_city: Optional[str] = None
    prop_mail_cmra: Optional[str] = None
    prop_mail_company: Optional[str] = None
    prop_mail_corrections: Optional[str] = None
    prop_mail_crrt: Optional[str] = None
    prop_mail_deliverable: Optional[str] = None
    prop_mail_dpv: Optional[str] = None
    prop_mail_dpv_notes: Optional[str] = None
    prop_mail_error_code: Optional[str] = None
    prop_mail_false_positive: Optional[str] = None
    prop_mail_house_num: Optional[str] = None
    prop_mail_left_overs: Optional[str] = None
    prop_mail_line_of_travel: Optional[str] = None
    prop_mail_no_stats: Optional[str] = None
    prop_mail_pbsa: Optional[str] = None
    prop_mail_post_dir: Optional[str] = None
    prop_mail_pre_dir: Optional[str] = None
    prop_mail_rdi: Optional[str] = None
    prop_mail_result_code: Optional[str] = None
    prop_mail_state: Optional[str] = None
    prop_mail_street: Optional[str] = None
    prop_mail_street2: Optional[str] = None
    prop_mail_street_name: Optional[str] = None
    prop_mail_sud: Optional[str] = None
    prop_mail_suffix: Optional[str] = None
    prop_mail_suite: Optional[str] = None
    prop_mail_unit_num: Optional[str] = None
    prop_mail_usps_bar_code: Optional[str] = None
    prop_mail_vacant_status: Optional[str] = None
    prop_mail_zip: Optional[str] = None
    prop_mail_zip4: Optional[str] = None
    property_class: Optional[str] = None
    property_location: Optional[str] = None
    qual: Optional[str] = None
    rate_year: Optional[str] = None
    ratio: Optional[float] = None
    ratio_year: Optional[str] = None
    reverse_parties: Optional[str] = None
    sale_date: Optional[str] = None
    sale_price: Optional[float] = None
    senior_citizens_cnt: Optional[str] = None
    sp_tax_cd_1: Optional[str] = None
    sp_tax_cd_2: Optional[str] = None
    sp_tax_cd_3: Optional[str] = None
    sp_tax_cd_4: Optional[str] = None
    sq_ft: Optional[int] = None
    street_1: Optional[str] = None
    street_2: Optional[str] = None
    street_3: Optional[str] = None
    street_4: Optional[str] = None
    surv_spouse_cnt: Optional[str] = None
    tax_rate: Optional[str] = None
    tax_ratio: Optional[str] = None
    taxes_1: Optional[float] = None
    taxes_2: Optional[float] = None
    taxes_3: Optional[float] = None
    taxes_4: Optional[float] = None
    total_assmnt_1: Optional[float] = None
    total_assmnt_2: Optional[float] = None
    total_assmnt_3: Optional[float] = None
    total_assmnt_4: Optional[float] = None
    type_use: Optional[str] = None
    updated: Optional[str] = None
    upi: Optional[str] = None
    veterans_cnt: Optional[str] = None
    widows_cnt: Optional[str] = None
    year_1: Optional[int] = None
    year_2: Optional[int] = None
    year_3: Optional[int] = None
    year_4: Optional[int] = None
    yr_built: Optional[int] = None
    yr_built_raw: Optional[str] = None
    zone: Optional[str] = None
    zone_def: Optional[str] = None

    """
    lat_lng: Optional[LatLng] = None
    parcel_centroid: Optional[ParcelCentroid] = None
    rooftop: Optional[Rooftop] = None
    """


class MunicipalityTaxRate(SQLModel_, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    municipality_id: Optional[int] = Field(default=None, index=True, foreign_key="municipalities.id")
    year: int
    tax_rate: Optional[float] = None
    ratio: Optional[float] = None


class MunicipalityData(SQLModel, table=True):
    __tablename__ = "municipalities"
    id: Optional[int] = Field(default=None, primary_key=True)
    assessor_email: Optional[str] = None
    assessor_name: Optional[str] = None
    assessor_phone: Optional[str] = None
    assessor_website: Optional[str] = None
    clerk_email: Optional[str] = None
    clerk_fax: Optional[str] = None
    clerk_name: Optional[str] = None
    clerk_phone: Optional[str] = None
    clerk_website: Optional[str] = None
    codebook_homepage: Optional[str] = None
    codebook_zoning: Optional[str] = None
    county: Optional[str] = None
    d_clerk_email: Optional[str] = None
    d_clerk_name: Optional[str] = None
    d_clerk_phone: Optional[str] = None
    eng_email: Optional[str] = None
    eng_name: Optional[str] = None
    eng_phone: Optional[str] = None
    eng_website: Optional[str] = None
    municipality: Optional[str] = None
    name: Optional[str] = None
    opra_url: Optional[str] = None
    website: Optional[str] = None
    # tax_rates = Optional[list[MunicipalityTaxRate]] = None


class NearbyProperty(SQLModel_, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    property_id: int = Field(index=True, foreign_key="properties.id")
    gis_pin: str
    property_location: Optional[str] = None


class PropertyDeed(SQLModel_, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    property_id: int = Field(index=True, foreign_key="properties.id")
    addl_block_1: Optional[str] = None
    addl_block_2: Optional[str] = None
    addl_block_3: Optional[str] = None
    addl_block_4: Optional[str] = None
    addl_block_5: Optional[str] = None
    addl_lot_1: Optional[str] = None
    addl_lot_2: Optional[str] = None
    addl_lot_3: Optional[str] = None
    addl_lot_4: Optional[str] = None
    addl_lot_5: Optional[str] = None
    addl_qualifier_1: Optional[str] = None
    addl_qualifier_2: Optional[str] = None
    addl_qualifier_3: Optional[str] = None
    addl_qualifier_4: Optional[str] = None
    addl_qualifier_5: Optional[str] = None
    addl_value_bldg_1: Optional[int] = None
    addl_value_bldg_2: Optional[int] = None
    addl_value_bldg_3: Optional[int] = None
    addl_value_bldg_4: Optional[int] = None
    addl_value_bldg_5: Optional[int] = None
    addl_value_land_1: Optional[int] = None
    addl_value_land_2: Optional[int] = None
    addl_value_land_3: Optional[int] = None
    addl_value_land_4: Optional[int] = None
    addl_value_land_5: Optional[int] = None
    addl_value_total_1: Optional[int] = None
    addl_value_total_2: Optional[int] = None
    addl_value_total_3: Optional[int] = None
    addl_value_total_4: Optional[int] = None
    addl_value_total_5: Optional[int] = None
    aging_date: Optional[str] = None
    appeal_status: Optional[str] = None
    assess_year: Optional[int] = None
    assessed_value_bldg: Optional[int] = None
    assessed_value_land: Optional[int] = None
    assessed_value_total: Optional[int] = None
    assessor_nu_code: Optional[str] = None
    assessor_written_cd: Optional[str] = None
    batch_number: Optional[str] = None
    block: Optional[str] = None
    block_suffix: Optional[str] = None
    class_4_type: Optional[str] = None
    condo: Optional[str] = None
    county_code: Optional[str] = None
    county_name: Optional[str] = None
    critical_error_flag: Optional[str] = None
    date_recorded: Optional[str] = None
    date_typed: Optional[str] = None
    deed_book: Optional[str] = None
    deed_date: Optional[str] = None
    deed_page: Optional[str] = None
    district_code: Optional[str] = None
    district_name: Optional[str] = None
    dln: Optional[str] = None
    etc: Optional[str] = None
    field_date: Optional[str] = None
    field_status_code: Optional[str] = None
    gis_pin: Optional[str] = None
    grantee_city_state: Optional[str] = None
    grantee_mail_city: Optional[str] = None
    grantee_mail_company: Optional[str] = None
    grantee_mail_corrections: Optional[str] = None
    grantee_mail_crrt: Optional[str] = None
    grantee_mail_dpv: Optional[str] = None
    grantee_mail_error_code: Optional[str] = None
    grantee_mail_house_num: Optional[str] = None
    grantee_mail_left_overs: Optional[str] = None
    grantee_mail_post_dir: Optional[str] = None
    grantee_mail_pre_dir: Optional[str] = None
    grantee_mail_rdi: Optional[str] = None
    grantee_mail_result_code: Optional[str] = None
    grantee_mail_state: Optional[str] = None
    grantee_mail_street: Optional[str] = None
    grantee_mail_street2: Optional[str] = None
    grantee_mail_street_name: Optional[str] = None
    grantee_mail_sud: Optional[str] = None
    grantee_mail_suffix: Optional[str] = None
    grantee_mail_suite: Optional[str] = None
    grantee_mail_unit_num: Optional[str] = None
    grantee_mail_zip: Optional[str] = None
    grantee_mail_zip4: Optional[str] = None
    grantee_name: Optional[str] = None
    grantee_street: Optional[str] = None
    grantee_zip: Optional[str] = None
    grantor_city_state: Optional[str] = None
    grantor_mail_city: Optional[str] = None
    grantor_mail_company: Optional[str] = None
    grantor_mail_corrections: Optional[str] = None
    grantor_mail_crrt: Optional[str] = None
    grantor_mail_dpv: Optional[str] = None
    grantor_mail_error_code: Optional[str] = None
    grantor_mail_house_num: Optional[str] = None
    grantor_mail_left_overs: Optional[str] = None
    grantor_mail_post_dir: Optional[str] = None
    grantor_mail_pre_dir: Optional[str] = None
    grantor_mail_rdi: Optional[str] = None
    grantor_mail_result_code: Optional[str] = None
    grantor_mail_state: Optional[str] = None
    grantor_mail_street: Optional[str] = None
    grantor_mail_street2: Optional[str] = None
    grantor_mail_street_name: Optional[str] = None
    grantor_mail_sud: Optional[str] = None
    grantor_mail_suffix: Optional[str] = None
    grantor_mail_suite: Optional[str] = None
    grantor_mail_unit_num: Optional[str] = None
    grantor_mail_zip: Optional[str] = None
    grantor_mail_zip4: Optional[str] = None
    grantor_name: Optional[str] = None
    grantor_nctl: Optional[str] = None
    grantor_street: Optional[str] = None
    grantor_zip: Optional[str] = None
    id: Optional[int] = None
    is_redacted: Optional[bool] = None
    last_update_date: Optional[str] = None
    living_space: Optional[str] = None
    lot: Optional[str] = None
    lot_suffix: Optional[str] = None
    match_method: Optional[str] = None
    operator_initials: Optional[str] = None
    property_class: Optional[str] = None
    property_location: Optional[str] = None
    qualification_codes: Optional[str] = None
    questionnaire_date: Optional[str] = None
    questionnaire_status_code: Optional[str] = None
    questionnaire_who_code: Optional[str] = None
    realty_transfer_fee: Optional[int] = None
    reported_sales_price: Optional[int] = None
    rtf_error_flag: Optional[str] = None
    rtf_exempt_code: Optional[str] = None
    sales_ratio: Optional[str] = None
    serial_number: Optional[str] = None
    sr_nu_code: Optional[str] = None
    u_n_type: Optional[str] = None
    verified_sales_price: Optional[int] = None
    year: Optional[int] = None
    year_built: Optional[int] = None


class PropertyForeclosure(SQLModel_, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    property_id: int = Field(index=True, foreign_key="properties.id")
    area_building: Optional[int] = None
    area_building_definition_code: Optional[str] = None
    area_lot_acres: Optional[float] = None
    area_lot_sf: Optional[float] = None
    attom_id: Optional[int] = None
    auction_address: Optional[str] = None
    auction_city: Optional[str] = None
    auction_date: Optional[str] = None
    auction_direction: Optional[str] = None
    auction_house_number: Optional[str] = None
    auction_post_direction: Optional[str] = None
    auction_street_name: Optional[str] = None
    auction_suffix: Optional[str] = None
    auction_time: Optional[str] = None
    auction_unit: Optional[str] = None
    bath_count: Optional[int] = None
    bedrooms_count: Optional[int] = None
    borrower_name_owner: Optional[str] = None
    case_number: Optional[str] = None
    courthouse: Optional[str] = None
    create_date: Optional[str] = None
    default_amount: Optional[int] = None
    estimated_value: Optional[float] = None
    foreclosure_book_page: Optional[str] = None
    foreclosure_instrument_date: Optional[str] = None
    foreclosure_instrument_number: Optional[str] = None
    foreclosure_recording_date: Optional[str] = None
    geo_quality: Optional[str] = None
    judgment_amount: Optional[float] = None
    judgment_date: Optional[str] = None
    lender_address: Optional[str] = None
    lender_address_city: Optional[str] = None
    lender_address_house_number: Optional[str] = None
    lender_address_state: Optional[str] = None
    lender_address_street_direction: Optional[str] = None
    lender_address_street_name: Optional[str] = None
    lender_address_street_post_direction: Optional[str] = None
    lender_address_street_suffix: Optional[str] = None
    lender_address_unit_value: Optional[str] = None
    lender_address_zip: Optional[str] = None
    lender_name_full_standardized: Optional[str] = None
    lender_phone: Optional[str] = None
    loan_balance: Optional[float] = None
    loan_maturity_date: Optional[str] = None
    original_loan_amount: Optional[float] = None
    original_loan_book_page: Optional[str] = None
    original_loan_instrument_number: Optional[str] = None
    original_loan_interest_rate: Optional[str] = None
    original_loan_loan_number: Optional[str] = None
    original_loan_recording_date: Optional[str] = None
    parcel_number_formatted: Optional[str] = None
    payment: Optional[str] = None
    penalty_interest: Optional[str] = None
    property_address_city: Optional[str] = None
    property_address_crrt: Optional[str] = None
    property_address_full: Optional[str] = None
    property_address_house_number: Optional[str] = None
    property_address_info_privacy: Optional[str] = None
    property_address_state: Optional[str] = None
    property_address_street_direction: Optional[str] = None
    property_address_street_name: Optional[str] = None
    property_address_street_post_direction: Optional[str] = None
    property_address_street_suffix: Optional[str] = None
    property_address_unit_prefix: Optional[str] = None
    property_address_unit_value: Optional[str] = None
    property_address_zip: Optional[str] = None
    property_address_zip4: Optional[str] = None
    property_jurisdiction_name: Optional[str] = None
    property_latitude: Optional[float] = None
    property_longitude: Optional[float] = None
    property_use_group: Optional[str] = None
    property_use_muni: Optional[str] = None
    property_use_standardized: Optional[str] = None
    publication_date: Optional[str] = None
    record_last_updated: Optional[str] = None
    record_type: Optional[str] = None
    recorded_auction_opening_bid: Optional[int] = None
    servicer_address: Optional[str] = None
    servicer_city: Optional[str] = None
    servicer_name: Optional[str] = None
    servicer_phone: Optional[str] = None
    servicer_state: Optional[str] = None
    servicer_zip: Optional[str] = None
    situs_county: Optional[str] = None
    situs_state_code: Optional[str] = None
    situs_state_county_fips: Optional[str] = None
    transaction_id: Optional[int] = None
    trustee_address: Optional[str] = None
    trustee_address_city: Optional[str] = None
    trustee_address_house_number: Optional[str] = None
    trustee_address_state: Optional[str] = None
    trustee_address_street_direction: Optional[str] = None
    trustee_address_street_name: Optional[str] = None
    trustee_address_street_post_direction: Optional[str] = None
    trustee_address_street_suffix: Optional[str] = None
    trustee_address_unit_value: Optional[str] = None
    trustee_address_zip: Optional[str] = None
    trustee_name: Optional[str] = None
    trustee_phone: Optional[str] = None
    trustee_reference_number: Optional[str] = None
    year_built: Optional[int] = None
    year_built_effective: Optional[str] = None
    zoned_code_local: Optional[str] = None


class PropertyHistory(SQLModel_, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    property_id: int = Field(index=True, foreign_key="properties.id")
    acreage: Optional[float] = None
    addition_lots_2: Optional[str] = None
    additional_lots: Optional[str] = None
    bank_code: Optional[str] = None
    block: Optional[str] = None
    building_assmnt_1: Optional[str] = None
    building_class: Optional[int] = None
    building_desc: Optional[str] = None
    city_state: Optional[str] = None
    city_state_zip: Optional[str] = None
    data_year: Optional[int] = None
    deduction_amount: Optional[str] = None
    deed_book: Optional[str] = None
    deed_page: Optional[str] = None
    delinquent_code: Optional[str] = None
    disabled_cnt: Optional[str] = None
    epl_desc: Optional[str] = None
    epl_facility_name: Optional[str] = None
    epl_further: Optional[str] = None
    epl_init: Optional[str] = None
    epl_own: Optional[str] = None
    epl_statute: Optional[str] = None
    epl_use: Optional[str] = None
    exemption_amt_1: Optional[str] = None
    exemption_amt_2: Optional[str] = None
    exemption_amt_3: Optional[str] = None
    exemption_amt_4: Optional[str] = None
    exemption_code_1: Optional[str] = None
    exemption_code_2: Optional[str] = None
    exemption_code_3: Optional[str] = None
    exemption_code_4: Optional[str] = None
    gis_pin: Optional[str] = None
    land_assmnt_1: Optional[str] = None
    land_desc: Optional[str] = None
    last_year_tax: Optional[str] = None
    lot: Optional[str] = None
    map_page: Optional[str] = None
    match_method: Optional[str] = None
    multiple_occupancy: Optional[str] = None
    municipality: Optional[str] = None
    no_of_commercial_dw: Optional[str] = None
    no_of_dwellings: Optional[str] = None
    nu_code: Optional[str] = None
    number_of_owners: Optional[str] = None
    old_property_id: Optional[str] = None
    owners_mailing_address: Optional[str] = None
    owners_name: Optional[str] = None
    percent_owned_code: Optional[str] = None
    prior_gis_pin: Optional[str] = None
    property_class: Optional[str] = None
    property_flags: Optional[str] = None
    property_location: Optional[str] = None
    property_use_code: Optional[str] = None
    qual: Optional[str] = None
    rebate_base_year: Optional[str] = None
    rebate_base_year_net_val: Optional[str] = None
    rebate_base_year_tax: Optional[str] = None
    rebate_code: Optional[str] = None
    rebate_response_flg: Optional[str] = None
    record_id: Optional[str] = None
    sale_assessment: Optional[str] = None
    sale_date: Optional[str] = None
    sale_price: Optional[int] = None
    sale_sr1_a_un_code: Optional[str] = None
    sales_price_code: Optional[str] = None
    senior_citizens_cnt: Optional[str] = None
    sp_tax_cd_1: Optional[str] = None
    sp_tax_cd_2: Optional[str] = None
    sp_tax_cd_3: Optional[str] = None
    sp_tax_cd_4: Optional[str] = None
    street_address: Optional[str] = None
    surv_spouse_cnt: Optional[str] = None
    total_assmnt_1: Optional[int] = None
    total_assmnt_2: Optional[int] = None
    transaction_update_no: Optional[str] = None
    updated: Optional[str] = None
    user_field_1: Optional[str] = None
    user_field_2: Optional[str] = None
    veterans_cnt: Optional[str] = None
    widows_cnt: Optional[str] = None
    yr_built: Optional[int] = None
    zip_code: Optional[str] = None
    zone: Optional[str] = None


class PropertyMortgage(SQLModel_, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    property_id: int = Field(index=True, foreign_key="properties.id")
    adjustable_rate_index: Optional[str] = None
    adjustable_rate_rider: Optional[str] = None
    assessors_land_use: Optional[str] = None
    assessors_parcel_number: Optional[str] = None
    borrower_fname_mname_1: Optional[str] = None
    borrower_fname_mname_2: Optional[str] = None
    borrower_id_code_1: Optional[str] = None
    borrower_id_code_1_description: Optional[str] = None
    borrower_id_code_2: Optional[str] = None
    borrower_id_code_2_description: Optional[str] = None
    borrower_lname_or_corpname_1: Optional[str] = None
    borrower_lname_or_corpname_2: Optional[str] = None
    borrower_mail_city: Optional[str] = None
    borrower_mail_state: Optional[str] = None
    borrower_mail_unit_number: Optional[str] = None
    borrower_mail_zip_code: Optional[str] = None
    borrower_mail_zipplus4: Optional[str] = None
    borrower_vesting_code: Optional[str] = None
    borrower_vesting_code_description: Optional[str] = None
    buyer_mail_full_street_address: Optional[str] = None
    cash_purchase: Optional[str] = None
    change_index: Optional[str] = None
    construction_loan: Optional[str] = None
    due_date: Optional[str] = None
    equity_credit_line: Optional[str] = None
    fips_code: Optional[str] = None
    first_change_date_month_day_conversion_rider: Optional[str] = None
    first_change_date_year_conversion_rider: Optional[str] = None
    fixedstep_conversion_rate_rider: Optional[str] = None
    gis_pin: Optional[str] = None
    id: Optional[int] = None
    interest_only_period: Optional[str] = None
    interest_rate: Optional[str] = None
    interest_rate_not_greater_than: Optional[str] = None
    interest_rate_not_less_than: Optional[str] = None
    legal_block: Optional[str] = None
    legal_brief_description: Optional[str] = None
    legal_city_township_municipality: Optional[str] = None
    legal_district: Optional[str] = None
    legal_land_lot: Optional[str] = None
    legal_lot_number: Optional[str] = None
    legal_phase_number: Optional[str] = None
    legal_section: Optional[str] = None
    legal_sectiontownship_rangemeridian: Optional[str] = None
    legal_subdivision_name: Optional[str] = None
    legal_tract_number: Optional[str] = None
    legal_unit: Optional[str] = None
    lender_dba_name: Optional[str] = None
    lender_mail_city: Optional[str] = None
    lender_mail_full_street_address: Optional[str] = None
    lender_mail_state: Optional[str] = None
    lender_mail_unit: Optional[str] = None
    lender_mail_zip_code: Optional[str] = None
    lender_mail_zipplus4: Optional[str] = None
    lender_name_beneficiary: Optional[str] = None
    lender_type: Optional[str] = None
    lender_type_description: Optional[str] = None
    loan_amount: Optional[str] = None
    loan_term_months: Optional[str] = None
    loan_term_years: Optional[str] = None
    loan_type: Optional[str] = None
    loan_type_description: Optional[str] = None
    maximum_interest_rate: Optional[str] = None
    original_date_of_contract: Optional[str] = None
    prepayment_rider: Optional[str] = None
    prepayment_term_penalty_rider: Optional[str] = None
    property_address_carrier_route: Optional[str] = None
    property_city_name: Optional[str] = None
    property_full_street_address: Optional[str] = None
    property_house_number: Optional[str] = None
    property_id: Optional[str] = None
    property_state: Optional[str] = None
    property_street_direction_left: Optional[str] = None
    property_street_direction_right: Optional[str] = None
    property_street_name: Optional[str] = None
    property_street_suffix: Optional[str] = None
    property_unit_number: Optional[str] = None
    property_unit_type: Optional[str] = None
    property_zip_code: Optional[str] = None
    property_zipplus4: Optional[str] = None
    purchase_money_mortgage: Optional[str] = None
    rate_change_frequency: Optional[str] = None
    record_type: Optional[str] = None
    record_type_description: Optional[str] = None
    recorders_book_number: Optional[str] = None
    recorders_document_number: Optional[str] = None
    recorders_page_number: Optional[str] = None
    recording_date: Optional[str] = None
    residential_indicator: Optional[str] = None
    standalone_refi: Optional[str] = None
    title_company_name: Optional[str] = None
    transaction_id: Optional[str] = None
    type_financing: Optional[str] = None
    type_financing_description: Optional[str] = None
    unique_link_id: Optional[str] = None


"""
class PropertyListing(SQLModel, table=True):
    acres: Optional[float] = None
    acrestax: Optional[str] = None
    addressincluded: Optional[str] = None
    agent2_listfirstname: Optional[str] = None
    agent2_listlastname: Optional[str] = None
    agent2_listofficephone: Optional[str] = None
    agent2_listpager: Optional[str] = None
    agent2_listphone: Optional[str] = None
    agentcolist: Optional[str] = None
    agentcosell: Optional[str] = None
    agentfirstname: Optional[str] = None
    agentid: Optional[str] = None
    agentlastname: Optional[str] = None
    agentofficefeed: Optional[str] = None
    agentofficephone: Optional[str] = None
    agentpager: Optional[str] = None
    agentphone: Optional[str] = None
    agentsell: Optional[str] = None
    anticcloseddate: Optional[str] = None
    appfee: Optional[str] = None
    appliances: Optional[str] = None
    arip: Optional[str] = None
    assessamountbldg: Optional[str] = None
    assessamountbldgtax: Optional[str] = None
    assessamountland: Optional[str] = None
    assessamountlandtax: Optional[str] = None
    assessfarm: Optional[str] = None
    assesstotaltax: Optional[str] = None
    assocfeefreq: Optional[str] = None
    associationfee: Optional[str] = None
    associationyn: Optional[str] = None
    assocmgmtname: Optional[str] = None
    assocmgmtphone: Optional[str] = None
    attachedgarageyn: Optional[str] = None
    basedesc: Optional[str] = None
    basement: Optional[str] = None
    baths: Optional[str] = None
    bathsdesc: Optional[str] = None
    bathsfull: Optional[str] = None
    bathshalf: Optional[str] = None
    bed1_level: Optional[str] = None
    bed2_level: Optional[str] = None
    bed3_level: Optional[str] = None
    bed4_level: Optional[str] = None
    bedroom1_dim: Optional[str] = None
    bedroom2_dim: Optional[str] = None
    bedroom3_dim: Optional[str] = None
    bedroom4_dim: Optional[str] = None
    beds: Optional[str] = None
    blockid: Optional[str] = None
    blockidtax: Optional[str] = None
    buildingnum: Optional[str] = None
    busrelation: Optional[str] = None
    buyeragentkey: Optional[str] = None
    buyerofficekey: Optional[str] = None
    carportyn: Optional[str] = None
    city: Optional[str] = None
    closedate: Optional[str] = None
    closeprice: Optional[str] = None
    cobuyeragentkey: Optional[str] = None
    colistagentkey: Optional[str] = None
    colistagentname: Optional[str] = None
    commliving: Optional[str] = None
    compbuy: Optional[str] = None
    complexfeatures: Optional[str] = None
    compsell: Optional[str] = None
    comptrans: Optional[str] = None
    condominium: Optional[str] = None
    confidentialincluded: Optional[str] = None
    contractdate: Optional[str] = None
    cooling: Optional[str] = None
    cosellagentname: Optional[str] = None
    county: Optional[str] = None
    county_data: Optional[CountyData] = None
    countycode: Optional[str] = None
    countycodetax: Optional[str] = None
    countytax: Optional[str] = None
    daysonmarket: Optional[int] = None
    diningroomdim: Optional[str] = None
    directions: Optional[str] = None
    disclosureavail: Optional[str] = None
    domact: Optional[int] = None
    domcomp: Optional[str] = None
    drivewaydesc: Optional[str] = None
    easedesc: Optional[str] = None
    easement: Optional[str] = None
    elementaryschool: Optional[str] = None
    exclusions: Optional[str] = None
    expirationdate: Optional[str] = None
    exterior: Optional[str] = None
    exteriorfeatures: Optional[str] = None
    familyroomdim: Optional[str] = None
    farm: Optional[str] = None
    feeincludes: Optional[str] = None
    feeother: Optional[str] = None
    feeotherfreq: Optional[str] = None
    fhaagerestr: Optional[str] = None
    fireplacedesc: Optional[str] = None
    fireplaces: Optional[str] = None
    fireplaceyn: Optional[str] = None
    firstshowingdate: Optional[str] = None
    floornum: Optional[str] = None
    floors: Optional[str] = None
    garage: Optional[str] = None
    garagedesc: Optional[str] = None
    gis_pin: Optional[str] = None
    handicap: Optional[str] = None
    heating: Optional[str] = None
    heatsrc: Optional[str] = None
    highschool: Optional[str] = None
    idx_flag: Optional[str] = None
    imagecount: Optional[int] = None
    imagedate: Optional[str] = None
    images: Optional[list[str]] = None
    interiorfeatures: Optional[str] = None
    kitchendim: Optional[str] = None
    lastmodified: Optional[str] = None
    latitude: Optional[float] = None
    lenderapproval: Optional[str] = None
    listagentkey: Optional[str] = None
    listagentname: Optional[str] = None
    listagentphone: Optional[str] = None
    listdate: Optional[str] = None
    listingid: Optional[str] = None
    listingstatus: Optional[str] = None
    listingtype: Optional[str] = None
    listofficefax: Optional[str] = None
    listofficekey: Optional[str] = None
    listofficename: Optional[str] = None
    listofficephone: Optional[str] = None
    listprice: Optional[str] = None
    listtypereso: Optional[str] = None
    livingroomdim: Optional[str] = None
    loanterms: Optional[str] = None
    longitude: Optional[float] = None
    lotdesc: Optional[str] = None
    lotid: Optional[str] = None
    lotidtax: Optional[str] = None
    lotsize: Optional[str] = None
    lotsizetax: Optional[str] = None
    lstngsysid: Optional[str] = None
    majorchangetimestamp: Optional[str] = None
    middleschool: Optional[str] = None
    mlstatus: Optional[str] = None
    offficebrokerid: Optional[str] = None
    officefax: Optional[str] = None
    officeid: Optional[str] = None
    officename: Optional[str] = None
    officephone: Optional[str] = None
    officesell: Optional[str] = None
    officesellbrokerid: Optional[str] = None
    officesellfax: Optional[str] = None
    officesellname: Optional[str] = None
    officesellphone: Optional[str] = None
    openparking: Optional[str] = None
    originalentrydatetime: Optional[str] = None
    originallistprice: Optional[str] = None
    otherroom1_dim: Optional[str] = None
    otherroom2_dim: Optional[str] = None
    otherroom3_dim: Optional[str] = None
    otherroom4_dim: Optional[str] = None
    otheruse: Optional[str] = None
    outofcounty: Optional[str] = None
    ownernametax: Optional[str] = None
    ownerphone: Optional[str] = None
    ownershiptype: Optional[str] = None
    ownersname: Optional[str] = None
    pets: Optional[str] = None
    photoinstr: Optional[str] = None
    pool: Optional[str] = None
    pooldesc: Optional[str] = None
    possession: Optional[str] = None
    possessionreso: Optional[str] = None
    postalcode: Optional[str] = None
    propcolor: Optional[str] = None
    property_type: Optional[str] = None
    publicremarks: Optional[str] = None
    rcomzip: Optional[str] = None
    remarks: Optional[str] = None
    remarkspubadd: Optional[str] = None
    renovated: Optional[str] = None
    rental: Optional[str] = None
    requireofficeinfo: Optional[str] = None
    roof: Optional[str] = None
    roombaselvldesc: Optional[str] = None
    roomdendim: Optional[str] = None
    roomdenlevel: Optional[str] = None
    roomdiningdesc: Optional[str] = None
    roomdininglevel: Optional[str] = None
    roomfamilylevel: Optional[str] = None
    roomgroundlvldesc: Optional[str] = None
    roomkitchendesc: Optional[str] = None
    roomkitchenlevel: Optional[str] = None
    roomlivinglevel: Optional[str] = None
    roomlvl1_desc: Optional[str] = None
    roomlvl2_desc: Optional[str] = None
    roomlvl3_desc: Optional[str] = None
    roomlvlotherdesc: Optional[str] = None
    roommasterbeddesc: Optional[str] = None
    roomother1: Optional[str] = None
    roomother1_level: Optional[str] = None
    roomother2: Optional[str] = None
    roomother2_level: Optional[str] = None
    roomother3: Optional[str] = None
    roomother3_level: Optional[str] = None
    roomother4: Optional[str] = None
    roomother4_level: Optional[str] = None
    sellagent2_firstname: Optional[str] = None
    sellagent2_lastname: Optional[str] = None
    sellagent2_officephone: Optional[str] = None
    sellagent2_pager: Optional[str] = None
    sellagent2_phone: Optional[str] = None
    sellagentfirstname: Optional[str] = None
    sellagentlastname: Optional[str] = None
    sellagentname: Optional[str] = None
    sellagentofficephone: Optional[str] = None
    sellagentpager: Optional[str] = None
    sellagentphone: Optional[str] = None
    services: Optional[str] = None
    sewer: Optional[str] = None
    showinginstructions: Optional[str] = None
    showingtime_flag: Optional[str] = None
    showspecial: Optional[str] = None
    sign: Optional[str] = None
    sqftapprox: Optional[str] = None
    stateorprovince: Optional[str] = None
    streetname: Optional[str] = None
    streetnametax: Optional[str] = None
    streetnumber: Optional[str] = None
    streetnumdisplay: Optional[str] = None
    streetnumtax: Optional[str] = None
    style: Optional[str] = None
    styleprimary: Optional[str] = None
    subdivision: Optional[str] = None
    subproptype: Optional[str] = None
    suite: Optional[str] = None
    suitedes: Optional[str] = None
    taxamount: Optional[str] = None
    taxamounttax: Optional[str] = None
    taxassessedvaluation: Optional[str] = None
    taxid: Optional[str] = None
    taxidtax: Optional[str] = None
    taxrate: Optional[float] = None
    taxratetax: Optional[str] = None
    taxrateyear: Optional[int] = None
    taxyear: Optional[int] = None
    taxyeartax: Optional[str] = None
    totalrooms: Optional[int] = None
    towncode: Optional[str] = None
    towncodetax: Optional[str] = None
    townhouse: Optional[str] = None
    towntax: Optional[str] = None
    uid: Optional[str] = None
    unitnumber: Optional[str] = None
    utilities: Optional[str] = None
    vendor: Optional[str] = None
    warranty: Optional[str] = None
    water: Optional[str] = None
    waterfrontyn: Optional[str] = None
    waterheater: Optional[str] = None
    withdrawndate: Optional[str] = None
    yearbuilt: Optional[str] = None
    yearbuiltdesc: Optional[str] = None
    zipcodetax: Optional[str] = None
    zoning: Optional[str] = None
"""


class VoterRegistrationItem(SQLModel, table=True):
    __tablename__ = "voter_registrations"
    id: Optional[int] = Field(default=None, primary_key=True)
    property_id: int = Field(index=True, foreign_key="properties.id")
    apt_unit: Optional[str] = None
    city: Optional[str] = None
    congressional: Optional[str] = None
    county: Optional[str] = None
    display_id: Optional[str] = None
    district: Optional[str] = None
    dob: Optional[str] = None
    fire: Optional[str] = None
    first: Optional[str] = None
    freeholder: Optional[str] = None
    last: Optional[str] = None
    leg_id: Optional[str] = None
    legislative: Optional[str] = None
    location: Optional[str] = None
    middle: Optional[str] = None
    municipality: Optional[str] = None
    party: Optional[str] = None
    reg_date: Optional[str] = None
    school: Optional[str] = None
    status: Optional[str] = None
    street_base: Optional[str] = None
    street_name: Optional[str] = None
    street_num: Optional[str] = None
    street_post: Optional[str] = None
    street_pre: Optional[str] = None
    street_suff: Optional[str] = None
    suffix: Optional[str] = None
    ward: Optional[str] = None
    zip: Optional[str] = None


class PropertyTax(SQLModel_, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    property_id: int = Field(index=True, foreign_key="properties.id")
    amount: Optional[float] = None
    amount_diff: Optional[float] = None
    amount_diff_currency: Optional[float] = None
    difference_currency: Optional[float] = None
    difference_percent: Optional[float] = None
    improved: Optional[float] = None
    land: Optional[float] = None
    match_method: Optional[str] = None
    total: Optional[float] = None
    year: Optional[int] = None


# walkscore
class Walkscore(SQLModel_, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    property_id: int = Field(index=True, foreign_key="properties.id")
    walk_score: Optional[int]
    walk_description: Optional[str]
    bike_score: Optional[int]
    bike_description: Optional[str]


# schools
class School(SQLModel_, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    property_id: int = Field(index=True, foreign_key="properties.id")
    city: Optional[str] = None
    county: Optional[str] = None
    distance: Optional[float] = None
    district_id: Optional[int] = None
    district_name: Optional[str] = None
    fax: Optional[str] = None
    fipscounty: Optional[int] = None
    lat: Optional[float] = None
    level: Optional[str] = None
    level_codes: Optional[str] = None
    lon: Optional[float] = None
    name: Optional[str] = None
    nces_id: Optional[str] = None
    overview_url: Optional[str] = None
    phone: Optional[str] = None
    rating: Optional[str] = None
    school_summary: Optional[str] = None
    state: Optional[str] = None
    state_id: Optional[str] = None
    street: Optional[str] = None
    type: Optional[str] = None
    universal_id: Optional[str] = None
    web_site: Optional[str] = None
    year: Optional[int] = None
    zip: Optional[str] = None


# additional-data
class PotentiallyRelatedProperty(SQLModel_, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    property_id: int = Field(index=True, foreign_key="properties.id")
    account: Optional[str] = None
    acreage: Optional[float] = None
    additional_lots: Optional[str] = None
    additional_lots_parsed: Optional[str] = None
    assessed_1: Optional[float] = None
    assessed_2: Optional[float] = None
    assessed_3: Optional[float] = None
    assessed_4: Optional[float] = None
    bank_code: Optional[str] = None
    block: Optional[str] = None
    building_assmnt_1: Optional[float] = None
    building_assmnt_2: Optional[float] = None
    building_assmnt_3: Optional[float] = None
    building_assmnt_4: Optional[float] = None
    building_class: Optional[str] = None
    building_desc: Optional[str] = None
    city_state_zip: Optional[str] = None
    city_state_zip_1: Optional[str] = None
    city_state_zip_2: Optional[str] = None
    city_state_zip_3: Optional[str] = None
    city_state_zip_4: Optional[str] = None
    class_4_code: Optional[str] = None
    county_name: Optional[str] = None
    deduction_amount: Optional[float] = None
    deed_book: Optional[int] = None
    deed_page: Optional[int] = None
    direct_parties: Optional[str] = None
    disabled_cnt: Optional[str] = None
    district_name: Optional[str] = None
    epl_desc: Optional[str] = None
    epl_facility_name: Optional[str] = None
    epl_further: Optional[str] = None
    epl_init: Optional[str] = None
    epl_own: Optional[str] = None
    epl_statute: Optional[str] = None
    epl_use: Optional[str] = None
    exempt_1: Optional[float] = None
    exempt_2: Optional[float] = None
    exempt_3: Optional[float] = None
    exempt_4: Optional[float] = None
    gis_pin: Optional[str] = None
    land_assmnt_1: Optional[float] = None
    land_assmnt_2: Optional[float] = None
    land_assmnt_3: Optional[float] = None
    land_assmnt_4: Optional[float] = None
    land_desc: Optional[str] = None
    last_year_tax: Optional[str] = None
    lot: Optional[str] = None
    map_page: Optional[str] = None
    mortgage_account: Optional[str] = None
    municipality: Optional[str] = None
    nu_code: Optional[str] = None
    o_city: Optional[str] = None
    o_state: Optional[str] = None
    o_zip: Optional[str] = None
    owner_1: Optional[str] = None
    owner_2: Optional[str] = None
    owner_3: Optional[str] = None
    owner_4: Optional[str] = None
    owner_mail_city: Optional[str] = None
    owner_mail_cmra: Optional[str] = None
    owner_mail_company: Optional[str] = None
    owner_mail_corrections: Optional[str] = None
    owner_mail_crrt: Optional[str] = None
    owner_mail_deliverable: Optional[str] = None
    owner_mail_dpv: Optional[str] = None
    owner_mail_dpv_notes: Optional[str] = None
    owner_mail_error_code: Optional[str] = None
    owner_mail_false_positive: Optional[str] = None
    owner_mail_house_num: Optional[str] = None
    owner_mail_left_overs: Optional[str] = None
    owner_mail_line_of_travel: Optional[str] = None
    owner_mail_no_stats: Optional[str] = None
    owner_mail_pbsa: Optional[str] = None
    owner_mail_post_dir: Optional[str] = None
    owner_mail_pre_dir: Optional[str] = None
    owner_mail_rdi: Optional[str] = None
    owner_mail_result_code: Optional[str] = None
    owner_mail_state: Optional[str] = None
    owner_mail_street: Optional[str] = None
    owner_mail_street2: Optional[str] = None
    owner_mail_street_name: Optional[str] = None
    owner_mail_sud: Optional[str] = None
    owner_mail_suffix: Optional[str] = None
    owner_mail_suite: Optional[str] = None
    owner_mail_unit_num: Optional[str] = None
    owner_mail_usps_bar_code: Optional[str] = None
    owner_mail_vacant_status: Optional[str] = None
    owner_mail_zip: Optional[str] = None
    owner_mail_zip4: Optional[str] = None
    owners_mailing_address: Optional[str] = None
    owners_name: Optional[str] = None
    p_city: Optional[str] = None
    p_state: Optional[str] = None
    p_zip: Optional[str] = None
    prior_block: Optional[str] = None
    prior_gis_pin: Optional[str] = None
    prior_lot: Optional[str] = None
    prior_qual: Optional[str] = None
    prop_mail_city: Optional[str] = None
    prop_mail_cmra: Optional[str] = None
    prop_mail_company: Optional[str] = None
    prop_mail_corrections: Optional[str] = None
    prop_mail_crrt: Optional[str] = None
    prop_mail_deliverable: Optional[str] = None
    prop_mail_dpv: Optional[str] = None
    prop_mail_dpv_notes: Optional[str] = None
    prop_mail_error_code: Optional[str] = None
    prop_mail_false_positive: Optional[str] = None
    prop_mail_house_num: Optional[str] = None
    prop_mail_left_overs: Optional[str] = None
    prop_mail_line_of_travel: Optional[str] = None
    prop_mail_no_stats: Optional[str] = None
    prop_mail_pbsa: Optional[str] = None
    prop_mail_post_dir: Optional[str] = None
    prop_mail_pre_dir: Optional[str] = None
    prop_mail_rdi: Optional[str] = None
    prop_mail_result_code: Optional[str] = None
    prop_mail_state: Optional[str] = None
    prop_mail_street: Optional[str] = None
    prop_mail_street2: Optional[str] = None
    prop_mail_street_name: Optional[str] = None
    prop_mail_sud: Optional[str] = None
    prop_mail_suffix: Optional[str] = None
    prop_mail_suite: Optional[str] = None
    prop_mail_unit_num: Optional[str] = None
    prop_mail_usps_bar_code: Optional[str] = None
    prop_mail_vacant_status: Optional[str] = None
    prop_mail_zip: Optional[str] = None
    prop_mail_zip4: Optional[str] = None
    property_class: Optional[str] = None
    property_location: Optional[str] = None
    qual: Optional[str] = None
    rate_year: Optional[str] = None
    ratio: Optional[int] = None
    ratio_year: Optional[str] = None
    reverse_parties: Optional[str] = None
    sale_date: Optional[str] = None
    sale_price: Optional[int] = None
    senior_citizens_cnt: Optional[int] = None
    sp_tax_cd_1: Optional[str] = None
    sp_tax_cd_2: Optional[str] = None
    sp_tax_cd_3: Optional[str] = None
    sp_tax_cd_4: Optional[str] = None
    sq_ft: Optional[int] = None
    street_1: Optional[str] = None
    street_2: Optional[str] = None
    street_3: Optional[str] = None
    street_4: Optional[str] = None
    surv_spouse_cnt: Optional[int] = None
    tax_rate: Optional[float] = None
    tax_ratio: Optional[float] = None
    taxes_1: Optional[float] = None
    taxes_2: Optional[float] = None
    taxes_3: Optional[float] = None
    taxes_4: Optional[float] = None
    total_assmnt_1: Optional[float] = None
    total_assmnt_2: Optional[float] = None
    total_assmnt_3: Optional[float] = None
    total_assmnt_4: Optional[float] = None
    type_use: Optional[str] = None
    updated: Optional[str] = None
    upi: Optional[str] = None
    veterans_cnt: Optional[int] = None
    widows_cnt: Optional[int] = None
    year_1: Optional[int] = None
    year_2: Optional[int] = None
    year_3: Optional[int] = None
    year_4: Optional[int] = None
    yr_built: Optional[int] = None
    yr_built_raw: Optional[str] = None
    zone: Optional[str] = None


class PropertyBroadbandCoverage(SQLModel_, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    property_id: int = Field(index=True, foreign_key="properties.id")
    block_code: Optional[str] = None
    business: Optional[int] = None
    consumer: Optional[str] = None
    dba_name: Optional[str] = None
    frn: Optional[str] = None
    hoco_final: Optional[str] = None
    hoco_num: Optional[str] = None
    holding_company_name: Optional[str] = None
    log_rec_no: Optional[str] = None
    max_ad_down: Optional[float] = None
    max_ad_up: Optional[float] = None
    provider_id: Optional[str] = None
    provider_name: Optional[str] = None
    state_abbr: Optional[str] = None
    tech_code: Optional[str] = None


class PropertyCensusData(SQLModel, table=True):
    __tablename__ = "property_census"
    id: Optional[int] = Field(default=None, primary_key=True)
    property_id: int = Field(index=True, foreign_key="properties.id")
    census_block: Optional[str] = None
    census_code: Optional[str] = None
    census_county: Optional[str] = None
    census_state: Optional[str] = None
    census_tract: Optional[str] = None
    gis_pin: Optional[str] = None


class PropertyUtilities(SQLModel_, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    property_id: int = Field(index=True, foreign_key="properties.id")
    electric_provider: Optional[str] = None
    gas_provider: Optional[str] = None
    gis_pin: Optional[str] = None
    sewer_service_area: Optional[str] = None
    water_provider: Optional[str] = None


# demographics
class StatisticTypes(IntEnum):
    AGE = 1
    EDUCATION = 2
    HOUSEHOLD_SIZE = 3
    INCOME = 4
    RESIDENCE = 5
    SEX = 6


class DemographicStatistic(SQLModel_, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    demographics_id: int = Field(index=True, foreign_key="demographics.id")
    stat_type: int = 0
    name: str
    value: float


class Demographics(SQLModel_, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    property_id: int = Field(index=True, foreign_key="properties.id")
    # quick_facts
    average_age: Optional[float] = None
    average_household_income: Optional[int] = None
    average_household_size: Optional[float] = None
    children_percentage: Optional[float] = None
    education_percentage: Optional[float] = None
    employment_percentage: Optional[float] = None

    age: Optional[list[DemographicStatistic]] = None
    education: Optional[list[DemographicStatistic]] = None
    household_size: Optional[list[DemographicStatistic]] = None
    income: Optional[list[DemographicStatistic]] = None
    residence: Optional[list[DemographicStatistic]] = None
    sex: Optional[list[DemographicStatistic]] = None


# contaminated-sites


class ContaminatedSite(SQLModel_, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    property_id: int = Field(index=True, foreign_key="properties.id")
    address: Optional[str] = None
    category: Optional[str] = None
    comu_code: Optional[str] = None
    county: Optional[str] = None
    distance: Optional[float] = None
    munic: Optional[str] = None
    pi_name: Optional[str] = None
    rem_level: Optional[str] = None
    status: Optional[str] = None
    zip_code: Optional[str] = None
